import Config from 'react-native-config';

console.log(Config, 'Config......');
export const CREDENTIALS = {
    
    endpoint: Config.API_URL /**Value from environment configuration */,
    zoomAppKey: '',
    zoomAppSecret: '',
};

export const ENDPOINTS = {
    login: '/auth/login',
    forgot: 'auth/forgot-password',
    verifyEmail: 'auth/verify-email',
    reset: 'auth/reset',
    forgotReset: 'auth/new-password',
    disease: 'disease',
    patient: 'patient/',
    organization: 'organization/',
    mfaVerify: 'auth/verify-mfa-code',
    relatedPerson: 'relatedPerson',
    // relatedPerson : 'relatedPerson/getByPatientRef',
    settingUpdate: 'patient/update-settings',
    settingList: 'patient/get-settings',
    listManualReadings: 'devicemetric/reading',

    getObservationReading: 'observation',
    // addManualReadings:'patients/reading',
    // addManualReadings: 'devicemetric/reading',
    addManualReadings: 'observation',
    // settingUpdate : 'patient/update-settings',
    setting: 'patient/settings',
    inviteRelative: 'relatedPerson/create',
    validateToken: 'auth/validate-code',
    // deleteRelatedPerson : 'relatedPerson/delete',
    signupRelative: 'auth/signup',
    notificationList: 'patients/notification/get',
    notificationUpdate: 'patients/notification/update',
    updateInvitation: 'relatedPerson/update',
    medication: 'medication',
    notification: 'patients/notification',
    // notificationUpdate : 'patients/notification',
    // updateInvitation : 'relatedPerson/update',
    sessionCreate: 'session/create',
    // listPractitionar:'patient/get-practitioner',
    listPractitionar: 'practitioner',
    schedule: 'schedule',
    slots: 'schedule/patient',
    orgServiceCat: 'serviceCategory',
    // appointment:'appointment/create',
    //  appointmentList:'appointment/list',
    appointment: 'appointment',
    //  appointmentNote:'appointment/get-note',
    appointmentNote: 'note',
    // rescheduleAppointment:'appointment/get',
    // cancelAppointment:'appointment/cancel',
    programList: 'patient/program-history',
    //  appointmentUpdate:'appointment/update',
    deviceToken: 'deviceToken',
    programEnroll: 'program/enroll-patients',
    getFeedbackQuestion: 'questionnaire/',
    feedbackSubmit: 'questionnaireresponse',
    encounter: 'encounter',
    discover: 'discover/organization',
    getlistRequisitions: 'servicerequest',
    requisitionDetails: 'documentreference?serviceRequestId=',
    getlistPrescriptions: 'medicationrequest',
    questionnaireList: 'questionnaire/',
    saveQuestionnaireResponse: 'questionnaireresponse',
    prescriptionsDetails: 'documentreference?medicationRequestId=',
};
