export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  buttons: {
    login: 'Login',
    send: 'Send',
    backLogin: 'Back to Login',
    submit: 'Submit',
    save: 'Save Changes',
    request: 'Send Request',
    save1: 'Save',
    next: 'Next',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
    resultDashboard: 'Results Dashboard',
    appointments: 'Appointments',
    requestGuidance: 'Get Care',
    bleConnect: 'Bluetooth Connectivity',
    diseaseMgmt: 'Disease Management',
    medication: 'Medication',
  },
  medication: {
    addMedication: 'Add Medication',
    medicationName: 'Medication Name',
    dosage: 'Dosage',
    timeTake: 'Time to take',
    take: 'Take',
    nottaken: 'Not Taken',
    taken: 'Taken',
    beforemeal: 'Before meal',
    duration: 'Duration',
    pill: 'Pill',
  },
  login: {
    username: 'Enter Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Enter Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid Username/Password',
    usernameTitle: 'Username',
    passwordTitle: 'Password',
    forgotPassword: 'Forgot Password?',
    privacyPolicy: 'Privacy Policy',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    message: 'This screen has the iOS native large header.',
    name: 'Name',
    firstName: 'First Name',
    lastName: 'Last Name',
    namePlaceholder: 'Name',
    email: 'Email Id',
    emailPlaceholder: 'Email Id',
    phone: 'Phone number',
    phonePlaceholder: 'Phone number',
    dob: 'Date of Birth',
    dobPlaceholder: 'YYYY-MM-DD',
    gender: 'Select Gender',
    genderPlaceholder: 'Select',
    logout: 'Logout',
  },
  forgot: {
    title: 'Forgot Password',
    placeholder: 'Enter Email Address',
  },
  forgotPasswordSuccess: {
    title: 'Link Sent Successfully',
    subtitle: 'To continue resetting your password, please check your email',
    //  subtitle: 'Kindly check your Email. We share password reset link.',
  },
  resetPassword: {
    title: 'Set New Password',
    newPassPlaceholder: 'Enter New Password',
    confirmPassPlaceholder: 'Confirm Password',
    newPassTitle: 'New Password',
    confirmPassTitle: 'Confirm Password',
  },
  otpVerification: {
    title: 'OTP Verification',
    subtitle: 'Enter otp sent to your email address',
  },
  disease: {
    addName: 'Disease Name',
    desc: 'Description',
    placeholderName: 'Enter Disease Name',
    placeholderDesc: 'Write here...',
    addButton: 'Add Disease',
    updateBtn: 'Update Disease',
    reason: 'Reason for your visit ?',
    approxText: 'Approximate Wait Time',
    waitingNote:
      'All patients are seen in order of arrival. There may be exceptions',
    sessionReady: 'A practitioner is ready to see you',
  },
  session: {
    title: 'Sessions',
    upcoming: 'Upcoming',
    requested: 'Requested',
    completed: 'Completed',
    cancel: 'Cancel',
    join: 'Join',
    accept: 'Accept',
    reject: 'Reject',
    sessionDetails: 'Session Details',
    note: 'Note',
    reschedule: 'Reschedule',
  },
  chat: {
    chat: 'Chat',
  },
  bloodPressure: {
    title: 'Blood Pressure',
    subTitle: 'Heart Rate',
    scale: 'mmHg',
    scale1: 'kPa',
    scale2: 'psi',
    doingGreat: 'You are doing great!',
    short: 'blood_pressure',
    diastollic: 'Diastolic',
    systolic: 'Systolic',
    pulse: 'Pulse/min',
    deviceName: 'Blood Pressure Monitor',
    model: 'Model: 550BT',
  },
  bloodGlucose: {
    title: 'Blood Glucose',
    subTitle: 'Glucose',
    short: 'blood_glucose',
    scale: 'mg/dL',
    scale1: 'mmol/L',
    deviceName: 'Glucometer',
    model: 'Model: BG5S',
  },
  temperature: {
    title: 'Temperature',
    subTitle: 'Body Temperature',
    scale: '°C',
    scale1: '°F',
    short: 'temperature',
    deviceName: 'Thermometer',
    model: 'Model: PT3SBT',
  },
  oximeter: {
    title: 'Air Pulse Oximeter',
    subTitle: 'Heart Rate',
    subTitle1: 'Oxygen',
    subTitle2: 'Blood Oxygen',
    oxygen: 'oxygen',
    short: 'heart_rate',
    short1: 'oximeter',
    scale: 'bpm',
    scale1: 'SpO2%',
    deviceName: 'Oximeter',
    model: 'Model: PO3',
    name: 'Heart Rate',
  },
  weight: {
    title: 'Weight',
    short: 'weight',
    scale: 'kg',
    scale1: 'lbs',
    deviceName: 'Weight Scale',
    model: 'Model: HS2S',
  },
  validation: {
    title: 'Validation Error',
    empty: 'Field should not be empty',
    validEmail: 'Email is not valid',
    matchPass: 'Password is not matching',
    invalidPass:
      'Password should contain at least 1 uppercase, lowercase, numeric, and special character with minimum length of 8 characters',
    emptyPass: 'Password is empty',
    emptyAll: 'All fields are mandatory',
    invalidNumber: 'Provided input is not valid',
    invalidSingleDecimal: 'Field requires only 1 decimal place',
    invalidWholeNumber: 'Field requires whole numbers only',
    outOfRange: 'Field value is out of range',
  },
  settings: {
    title: 'Settings',
    email: 'Email Notification',
    message: 'New Message',
    request: 'Request Accepted',
    denied: 'Request Denied',
    session: 'Session Started',
    mfa: 'MFA enabled',
    mfa_full: 'Multi Factor Authentication enabled',
  },
  forgot: {
    title: 'Forgot Password',
    placeholder: 'Enter Email Address',
  },
  forgotPasswordSuccess: {
    title: 'Link Sent Successfully',
    subtitle: 'To continue resetting your password, please check your email',
    // subtitle: 'Kindly check your Email. We share password reset link.',
  },
  resetPassword: {
    title: 'Set New Password',
    newPassPlaceholder: 'Enter New Password',
    confirmPassPlaceholder: 'Confirm Password',
    newPassTitle: 'New Password',
    confirmPassTitle: 'Confirm Password',
  },
  otpVerification: {
    title: 'OTP Verification',
    subtitle: 'Enter otp sent to your email address',
  },

    settings: {
        title: 'Settings',
        email: 'Email Notification',
        message: 'New Message',
        request: 'Request Accepted',
        denied: 'Request Denied',
        session: 'Session Started',
        mfa: 'MFA enabled',
        mfa_full: 'Multi Factor Authentication enabled',
    },
    btn: {
        title: 'Add Data',
        invite: 'Invite',
    },
    forgot: {
        title: 'Forgot Password',
        placeholder: 'Enter Email Address',
    },
    resetTemp: {
        title: 'Reset temporary password',
        placeholder: 'Enter Email Address',
    },
    forgotPasswordSuccess: {
        title: 'Link Sent Successfully',
        subtitle: 'To continue resetting your password, please check your email',
        // subtitle: 'Kindly check your Email. We share password reset link.',
    },
    resetPassword: {
        title: 'Set New Password',
        newPassPlaceholder: 'Enter New Password',
        confirmPassPlaceholder: 'Confirm Password',
        newPassTitle: 'New Password',
        confirmPassTitle: 'Confirm Password',
        oldPassTitle: 'Old Password',
    },
    otpVerification: {
        title: 'Verification Code',
        subtitle: 'Enter the Verification Code sent to your email address',
    },

    settings: {
        title: 'Settings',
        email: 'Email Notification',
        message: 'New Message',
        request: 'Request Accepted',
        denied: 'Request Denied',
        session: 'Session Started',
        mfa: 'MFA enabled',
        mfa_full: 'Multi Factor Authentication Enabled',
        programs: 'Programs',
        list_programs: 'List Programs',
    },
    vital: {
        title: 'Vitals Monitoring',
        history: 'History',
        manual: 'Add Manual',
        addAutomatic: 'Add From Device',
        takeReading: 'Take a reading',
        latestReading: 'Latest Reading',
        prevReading: 'Previous Readings',
        readings: 'Readings',
    },
    others: {
        sync: 'Sync now',
    },
    dependent: {
        name: 'Related Person',
        title: 'Select Patient',
        //   subTitle: 'Kindly select app use for',
        subTitle: 'Please select account',
        self: 'SELF',
        noData: 'No dependent have been added yet.',
    },
    requisitions: {
        name: 'Requisitions',
        date: 'Date',
        time: 'Time',
        practitioner: 'Practitioner',
        requestType: 'Request Type',
    },
    requisitionDetails: {
        name: 'Requisition Details',
        encounterId: 'Encounter Id :',
        orgInfo: 'Organization Information',
        practInfo: 'Practitioner Information',
        patientInfo: 'Patient Information',
        nameKey: 'Name :',
        address: 'Address :',
        contact: 'Contact :',
        designation: 'Designation :',
        licanceNo: 'Licence No. :',
        sex: 'Sex :',
        dob: 'DOB :',
        testing: 'Testing Order List',
        practSign: 'Practitioner Signature',
        date: 'Date',
    },
    prescriptions: {
        name: 'Prescriptions',
        MedicationKey: 'Medication Name',
        date: 'Date',
    },
    prescriptionsDetails: {
        name: 'Prescriptions Details',
        MedicationKey: 'Medication Name',
        date: 'Date',
        dosage: 'Dosage',
        units: 'Units',
        route: 'Route',
        frequency: 'Frequency',
        practitioner: 'Practitioner',
        Instructions: 'Instructions/Notes:',
    },
    getCare: {
        name: 'Get Care',
        title: 'Select Get Care',
        subTitle: 'Kindly select app use for',
        self: 'SELF',
        noData: 'No Get Care have been added yet.',
        whoVisitFor: 'Who is the visit for?',
        reason: 'Reason for your visit ?',
    },
    invite: {
        title: 'Invite Person',
        gender: 'Select Gender',
        relation: 'Select Relationship',
    },
    notification: {
        title: 'Notifications',
        accept: 'Accept',
        reject: 'Reject',
        markAsRead: 'Read',
    },
    requestGuidance: {
        title: 'Get Care',
        header: 'Request care team contact',
        subheader:
            'Enter details below to request contact with a provider. If this is an emergency, please call 911',
        requestTitle: 'Request Title',
        care: 'Select Care Provider',
        urgency: 'Urgency',
        tweleve: 'Within 12 hours',
        twentyFour: 'Within 24 hours',
        two: 'Within 2 days',
        attach: 'Attach Files',
        upload: 'Upload a photo or a file',
        appointmentType: 'Appointment Type',
        selectType: 'Select Type',
        name: 'name',
        media: ' Media',
        attachment: 'Attachment',
        seeMore: 'See more',
    },
    bleConnect: {
        type: 'Devices Type',
        newDevice: 'Add New Device',
        bleTitle: 'BLE Devices',
    },
    type: {
        manual: 'manual',
        automatic: 'automatic',
    },
    feedback: {
        header: 'feedback',
        additionalComment: 'Please provide any Additional comments you would like to share.',
        submit: 'Submit',
        backHome: 'Back to Home',
        thanksText: 'Thank you',
        yourFeedback: 'for your feedback',
    },
    bookingList: {
        header: 'When would you like to see the provider?',
        questionnaire: 'Questions',
    },
    bookAppointment: {
        attachOptional: 'Attach File (optional)',
        format: 'Format of JPG, GIF, Word, or PDF',
        whichProvider: 'Which provider would you like to meet with?',
        care: 'Select Provider',
        appointmentSent: 'Appointment Request Sent',
        requestRecievedText: 'You will receive a notification once your request has been reviewed',
        returnHome: 'Return to Home',
    },
    waitingRoom: {
        btnSendRequest: 'Enter virtual waiting room',
        cancelRequest: 'Cancel Waiting Room Request',
    },
};
